### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by effigies**
See https://github.com/python-versioneer/python-versioneer/issues/315 + https://github.com/python-versioneer/python-versioneer/pull/317

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by effigies** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Chris! 🙏

Normally we update the license if there has been a new release that includes license changes. Has that happened? If so, can we go ahead and update to the latest version?

**Comment by effigies** [comment]
Yes, 0.24 was relicensed.

**Comment by jakirkham** [comment]
Ah I see. Thanks for clarifying 🙏

**Pull request merged**
