### PR TITLE
Change license

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

The repo https://github.com/python-versioneer/python-versioneer#license links to https://creativecommons.org/publicdomain/zero/1.0/ which has the same legal text as https://spdx.org/licenses/CC0-1.0.html so this should be the same, even if the names are slightly different.

It might make sense to include the actual license file?

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
@jakirkham Gentle reminder here :)

**Comment by BastianZim** [comment]
@jakirkham Gentle ping here :)

**Comment by jakirkham** [comment]
Sorry @BastianZim am not following this change. AFAICT upstream is still using [public domain]( https://github.com/python-versioneer/python-versioneer/blob/ca4e89a4c124d36ad668085450821384439f117e/setup.py#L135 ).

**Comment by BastianZim** [comment]
Yes but it's a specific public domain: https://github.com/python-versioneer/python-versioneer#license

**Comment by jakirkham** [comment]
Understand they updated it in that one place. However it is not in `setup.py` or [earlier in the same README]( https://github.com/python-versioneer/python-versioneer#the-versioneer ). Before updating here, it would be nice to see upstream do a more consistent job of updating this in the codebase.

**Comment by BastianZim** [comment]
Agreed. Let me open an issue there.

**Comment by BastianZim** [comment]
Issue is here: https://github.com/python-versioneer/python-versioneer/issues/291

**Comment by BastianZim** [comment]
License PR is in https://github.com/python-versioneer/python-versioneer/pull/292
As this PR has also some conflicts, I'm going to close it and would suggest updating the license part once a new version is released.

**Comment by jakirkham** [comment]
Thanks for following up with them 🙂

Next update we can do the same. Tracking here ( https://github.com/conda-forge/versioneer-feedstock/issues/16 )

**Pull request closed without merging**
